config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show

  resources :cars do
    resources :bookings, only: [:new, :create, :index, :destroy]

    resources :carphotos, only: [:index, :destroy]
    resources :reviews, only: [  :create ]
  end


  resources :bookings, only: :show

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  # validates :total_price, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews


  validates :make, presence: true
  validates :model, presence: true
  validates :mileage, presence: true
  validates :year, presence: true
  validates :color, presence: true
  validates :price_per_day, presence: true
  validates :location, presence: true

  has_many :carphotos, dependent: :destroy

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch
  pg_search_scope :search_by_make_model_location,
    against: [ :make, :model, :location ],
    associated_against: {
      user: [ :username ]
    },
    using: {
      tsearch: { prefix: true }
    }

end

app/models/carphoto.rb
class Carphoto < ApplicationRecord
  belongs_to :car

  mount_uploader :photo, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :content, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cars
  has_many :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :address, presence: true

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :address, :photo, :photo_cache])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo, :photo_cache])
  end

  # Pundit set-up: ------------------------- :

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [ :index, :show ], unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def show
    @booking = Booking.find(params[:id])
    pundit_booking
  end

  def new
    @booking = Booking.new
    @car = Car.find(params[:car_id])
    @booking.car = @car
    pundit_booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @car = Car.find(params[:car_id])
    @booking.car = @car
    pundit_booking
    @booking.total_price = @car.price_per_day * (@booking.end_date - @booking.start_date)
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  # def edit
  #   @booking = Booking.find(params[:id])
  #   pundit_booking
  # end

  def update
    @booking = Booking.find(params[:id])
    pundit_booking
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @user = @booking.user
    pundit_booking
    @booking.destroy
    redirect_to user_path(@user)
  end

   private

  def pundit_booking
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :car_id, :user_id)
  end
end

app/controllers/carphotos_controller.rb
class CarphotosController < ApplicationController
  def index
    # raise
    @carphotos = Car.find(params[:car_id]).carphotos
  end

  def destroy
    # raise
    @carphoto = Carphoto.find(params[:id])
    @carphoto.destroy
    authorize @carphoto
    redirect_to car_carphotos_path(params[:car_id])
  end

  private
  def carphoto_params
    params.require(:carphoto).permit(:id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    if params[:search].present?
       @cars = Car.search_by_make_model_location(params[:search])
    else
      @cars = Car.all
    end



    # def index # this will be needed if we have a map on the search page
    #   @flats = Flat.where.not(latitude: nil, longitude: nil)

    #   @markers = @flats.map do |flat|
    #     {
    #       lat: flat.latitude,
    #       lng: flat.longitude#,
    #       # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
    #     }
    #   end
    # end
  end

  def show
    @review = Review.new
    @car = Car.find(params[:id])
    @markers = [{
        lat: @car.latitude,
        lng: @car.longitude,
        infoWindow: { content: render_to_string(partial: "/cars/map_box", locals: { car: @car }) }
      }]
  end

  def new
    @car = Car.new
    punit_car
  end

  def create
    @car = Car.new(car_params)

    @car.user = current_user
    punit_car
    if @car.save
      if params["photos"]
        params["photos"]['photo'].each do |a|
          c = Carphoto.new(photo: a)
          c.car = @car
          c.save
        end
      end
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
    punit_car
  end

  def update
    @car = Car.find(params[:id])
    punit_car
    if @car.update(car_params)
      redirect_to car_path(@car)
    else
      render :edit
    end
  end

  def destroy
    @car = Car.find(params[:id])
    punit_car
    @car.destroy
    redirect_to cars_path
  end

  private

  def punit_car
    authorize @car
  end

  def car_params
    params.require(:car).permit(:make, :model, :year, :color, :mileage, :price_per_day, :location, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @car = Car.find(params[:car_id])
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    authorize @review
    # we need `car_id` to asssociate review with corresponding car
    @car = Car.find(params[:car_id])
    @review.car = @car

    if @review.save
      redirect_to car_path(@car)
    else
      render 'cars/show'
    end
  end

  def show
    @reviews = Review.select(params[:car_id])
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <h1 class="form-title">Make a booking</h1>
  <%= render "shared/booking_form" %>
</div>

app/views/bookings/show.html.erb
<h2 class="show-bookings-header">Your Booking</h2>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="booking-infocard">
        <div class="first-row">
           <div class="infocard-text">
            <p class="car"><strong>Car:</strong> <%= @booking.car.make %> <%= @booking.car.model %></p>
            <p class="total_price"><strong>Total price:</strong> £<%= @booking.total_price %></p>
            <p class="start_date"><strong>Start date: </strong> <%= @booking.start_date %></p>
            <p class="end_date"><strong>End date: </strong> <%= @booking.end_date %></p>
            <p class="owner"><strong>Owner:</strong> <%= link_to " #{@booking.car.user.first_name} #{@booking.car.user.last_name}", user_path(@booking.car.user) %> </p>
            <p class="borrower"><strong>Borrower:</strong> <%= link_to " #{@booking.user.first_name} #{@booking.user.last_name}", user_path(@booking.user) %> </p>
          </div>

          <%= cl_image_tag @booking.car.user.photo, gravity: "face", height: 400, width: 400, crop: "thumb", class: "owner-photo" %>
        </div>


        <div class="car-photo">
          <% if @booking.car.carphotos.first.photo %>
            <%= cl_image_tag @booking.car.carphotos.first.photo, width:485, height:300, crop: :fill, class: "car-photo" %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>






        <%# if policy(@booking).destroy? %>
        <%#= link_to "Delete booking", booking_path(@booking), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
      <%# end %>

app/views/carphotos/index.html.erb
<div class="container">
  <h1>Edit Photo Gallery</h1>

  <%= link_to "Add a car photo", "#", class: "btn btn-danger" %>

  <div class="viewport-min-heigth">
    <div class="row">

      <% @carphotos.each do |photo| %>
        <div class="col-xs-6 col-sm-3">
          <div class="gallery-img" style="background-image: url(<%= cl_image_path photo.photo %>);">
            <%= link_to car_carphoto_path(params[:car_id], photo), method: :delete do %>
              <i class="fas fa-trash-alt color-bin"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>


</div>

app/views/cars/_map_box.html.erb
<div>
  <p><%= @car.location %></p>
  <p>*****</p>
</div>

app/views/cars/edit.html.erb
<div class="container">
  <h1 class="add-car-form-title">Edit your car</h1>
  <%= render "shared/car_form" %>
</div>

app/views/cars/index.html.erb
<div class="container">
  <div class="wrapper">
    <div class="search-form">
      <%= render "shared/search_form" %>
    </div>
    <div class="row">
      <%= render "shared/card" %>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container">
  <h1 class="add-car-form-title">Add your car</h1>
  <%= render "shared/car_form" %>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="car-title">
        <h3><%= @car.make %> <%= @car.model %></h3>
        <% if policy(@car).update? %>
          <%= link_to "Edit car", edit_car_path(@car), class: "btn btn-danger" %>
          <%= link_to "Delete car", car_path(@car), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="address-info-data">
        <h3><%= @car.location %></h3>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="car-infocard">
        <p class="price-style">
          <strong>£<%= @car.price_per_day %></strong> per day
        </p>
        <%= render "shared/avg_star_rating", car: @car %>
        <ul class="car-card-list">
          <li>Make: <%= @car.make %></li>
          <li>Model: <%= @car.model %></li>
          <li>Year: <%= @car.year %></li>
          <li>Mileage: <%= @car.mileage %></li>
          <li>Color: <%= @car.color %></li>
        </ul>
        <div class="contact-row">
          <div>
            <%= link_to user_path(@car.user), class: :avatarNtext do %>
              <%= cl_image_tag @car.user.photo, gravity: "face", height: 400, width: 400, crop: "thumb", class: "avatar" %>
              <div class="contact-text">
                <p><strong><%= @car.user.first_name %></strong></p>
                <p><%= @car.user.address %></p>
              </div>
            <% end %>
          </div>
          <div>
            <%= link_to "Contact #{@car.user.first_name}", new_car_booking_path(@car), class: "btn btn-danger asign-btn-width" %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="map-card">
        <div
          id="map"
          style="width: 100%;
          height: 100%;"
          data-markers="<%= @markers.to_json %>"
        ></div>
      </div>
    </div>
  </div>

  <!-- Carousel row starts here -->
  <% if @car.carphotos.first %>

    <div class="row">
      <div class="col-sm-12 col-md-6 col-md-offset-3">
        <div class="holder">
          <div id="carousel-car" class="carousel slide" data-ride="carousel" data-interval="5000">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-car" data-slide-to="0" class="active"></li>
              <% (@car.carphotos.length - 1).times do |i| %>
                <li data-target="#carousel-car" data-slide-to="<%= i + 1 %>"></li>
              <% end %>
            </ol>
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <%= cl_image_tag @car.carphotos.first.photo, width:485, height: 300, crop:"fill", gravity:"auto", class: "fit-to-size" %>
              </div>
              <% @car.carphotos.drop(1).each do |photo_class| %>
                <div class="item">
                  <%= cl_image_tag photo_class.photo, width:485, height: 300, crop:"fill", gravity:"auto", class: "fit-to-size" %>
                </div>
              <% end %>
            </div>
            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-car" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-car" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div> <!-- Carousel -->
        </div>

        <% if policy(@car).update? %>
          <div class="center-btn-gallery">
            <%= link_to "Edit Photo Gallery", car_carphotos_path(@car), class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <!-- Carousel row ends here -->



  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="review">
        <h4>Reviews</h4>
        <ul>
          <li>
            <%= if @car.reviews.blank? then "Be the first to write a review!" end %>
          </li>
          <% @car.reviews.each do |review| %>
          <li>
            <% review.rating.to_i.times do %><i class="fas fa-star"></i>
            <% end %>
            <% (5 - review.rating.to_i).times do %><i class="far fa-star"></i>
            <% end %>
          <%= review.content %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="review">
        <h4>Write a Review</h4>
        <%= render "shared/review_form" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Carbnb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Swanky+and+Moo+Moo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <%= favicon_link_tag "tab_logo.png" %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>

    <%= render 'shared/flashes' %>

      <%= yield %>

    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper">

  <%= render 'shared/banner' %>



</div>

app/views/reviews/show.html.erb
<% @reviews.each do |review| %>
<%= review.rating %>
<%= review.content %>
<% end %>

app/views/shared/_avg_star_rating.html.erb
<% unless car.reviews.empty? %>
  <% full_stars = (car.reviews.sum(:rating).to_f/car.reviews.count).round %>
  <% empty_stars = 5 - full_stars%>
  <div class="rating">
    <% full_stars.times do %>
      <i class="fas fa-star"></i>
    <% end %>
    <% empty_stars.times do %>
      <i class="far fa-star"></i>
    <% end %>
  </div>
<% end %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(100,100,100,0.5) 0%, rgba(0,0,0,0.6) 50%), url(<%= image_path('background.jpg') %>);">
  <div class="banner-content">
    <h1>“Money may not buy happiness, but I’d rather cry in a Jaguar than on a bus”
    </h1>
    <p>Rent your dream car</p>
    <div class="search-form">
      <%= render "shared/search_form" %>
    </div>
  </div>
</div>

app/views/shared/_booking_form.html.erb
<div class="row">
  <div class="col-sm-12 col-md-6 col-md-offset-3">

    <%= simple_form_for [@car,@booking] do |f| %>

      <div class="booking-form">
        <p><strong>Price Per Day:</strong> £<%= @car.price_per_day %></p>

        <%= f.input :start_date, placeholder: "dd/mm/yyyy" %>

        <%= f.input :end_date, placeholder: "dd/mm/yyyy" %>

        <%= f.submit class: "btn btn-danger" %>

      </div>
    <% end %>

  </div>
</div>

app/views/shared/_car_form.html.erb
<div class="row">
  <div class="col-sm-12 col-md-6 col-md-offset-3">

    <%= simple_form_for @car do |f| %>
      <%= f.input :make, placeholder: "Make", label: false %>

      <%= f.input :model, placeholder: "Model", label: false %>

      <div class="dropdowns">

        <div class="selectWrapper">
          <div class="dropdown-year">
            <%= f.input :year, collection: 1920..2018, prompt: "Select year of manufacture", label: false %>
          </div>
        </div>

        <div class="selectWrapper">
          <div class="dropdown-color">
            <%= f.input :color, collection: ["black", "silver", "grey", "red", "yellow", "dark blue", "light blue", "orange", "white", "pink", "brown", "dark green", "light green", "purple"], prompt: "Color", label: false %>
          </div>
        </div>
      </div>


      <div class="input-group">
        <div class="input-group-addon">£</div>
        <%= f.input :price_per_day, placeholder: "Price/day", label: false, input_html: { class: 'input-group-fix-right' } %>
      </div>


      <div class="input-group">
        <%= f.input :mileage, placeholder: "Mileage", label: false, input_html: { class: 'input-group-fix-left' } %>
        <div class="input-group-addon">miles</div>
      </div>

      <%= f.input :location, placeholder: "Location: e.g. 138 Kingsland Road, London E2 8DY", label: false %>

      <% if params['action'] == "new" %>
        <%= f.fields_for :carphotos do |p| %>
          <%= f.file_field :photo, multiple: true, name: "photos[photo][]" %>
        <% end %>
      <% end %>


      <div class="add-car-submit-button">
        <%= f.submit class: "btn btn-danger"%>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_card.html.erb
<% @cars.each do |car| %>
  <%= link_to car_path(car) do %>
  <div class="col-xs-12 col-sm-6 col-md-4 ">
      <div class="card">

        <div class= "card-body" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= cl_image_path car.carphotos.first.photo unless car.carphotos.empty? %>);">
        </div>

        <div class="card-footer">

          <div class="car-details">
            <h4 class="car-name"><%= car.make %> <%= car.model %></h4>
          </div>

          <%= render "shared/avg_star_rating", car: car %>

          <div class="owner-section">
            <%= cl_image_tag car.user.photo, gravity: "face", height: 400, width: 400, crop: "thumb", class: "avatar avatar-small" %>
            <div class="owner-details">
              <h6><%= car.user.first_name %></h4>
              <h6><%= car.user.address %></h4>
            </div>
            <h5 class="price-per-day">£<%= car.price_per_day %>/day</h5>
          </div>

        </div>

      </div>

  </div>

  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <a href="#">Privacy<i class="link"></i></a>
    <a href="#">Copyright<i class="link"></i></a>
    <a href="#">Sitemap<i class="link"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="logo">
    <%= link_to image_tag('logo.png', style: "height: 30px;"), root_path, class: "navbar-wagon-brand" %>
    <%#= image_tag("example.png", :style => 'border-right: 1px solid #000;')%>
  </div>




  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Rent a Car", cars_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Lend my Car", new_car_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

          <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->

</div>

app/views/shared/_review_form.html.erb
    <%= simple_form_for [@car,@review] do |f| %>
      <div class="booking-form">
        <%= f.input :content, placeholder: "Write a review" %>
        <%= f.input :rating, placeholder: "Give a rating between 1 & 5", collection: (1..5) %>
        <%= f.submit class: "btn btn-danger" %>
      </div>
    <% end %>

app/views/shared/_search_form.html.erb
<%= form_tag cars_path, method: :get do %>
  <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Find a car by make, model, city or user" %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="dashboard-wrapper">
    <h1> <%= @user.username %> </h1>
    <div class="row">
      <div class="col-xs-12 col-md-12">
        <div class="content-box">
            <%= cl_image_tag @user.photo, gravity: "face", height: 400, width: 400, crop: "thumb" %>
        </div>
      </div>
      <div class="col-xs-12 col-md-12">
        <div class="content-box">
          <h1>Personal Details</h1>
          <div class="divider">
          <ul>
            <li>Username: <%= @user.username %></li>
            <li>First Name: <%= @user.first_name %></li>
            <li>Last Name: <%= @user.last_name %></li>
            <li>Address: <%= @user.address %></li>
            <li>Email: <%= @user.email %></li>
          </ul>
          <%= link_to "Edit Details", edit_user_registration_path, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="my-cars-content-box">
          <h1>My Bookings</h1>
          <div class="cars-list">
            <ul>
            <% @user.bookings.each do |booking| %>
              <li>
                <div class="row row-display-flex">
                  <div class="spacer-box">
                    <%= link_to "#{booking.start_date} - #{booking.car.make} #{booking.car.model} - #{booking.car.user.username} | ", booking_path(booking) %>
                  </div>
                 <div class="trash">
                   <%= link_to car_booking_path(booking.car, booking), method: :delete, data: {confirm: "Are you sure?"} do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                 </div>

                </div>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-6">
        <div class="my-cars-content-box">
          <h1>My Cars</h1>
          <div class="cars-list">
            <% @user.cars.each do |car| %>
            <ul>
              <li><%= link_to "#{car.make} #{car.model}", car_path(car) %></li>
            </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>